name = "paulm/minting"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'paulm/minting'"

[repository]
user = "paulm"
project = "minting"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
